CPP=g++
1: S5.E1.1.cpp
	$(CPP) S5.E1.1.cpp -o ~/public_html/cgi-bin/S5.E1.1.cgi
2: S5.E1.2.cpp
	$(CPP) S5.E1.2.cpp -o ~/public_html/cgi-bin/S5.E1.2.cgi
3: S5.E1.3.cpp
	$(CPP) S5.E1.3.cpp -o ~/public_html/cgi-bin/S5.E1.3.cgi
clean:
	rm ~/public_html/cgi-bin/S5.E1.[1-3].cgi
